# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculator.proto',
  package='calculator',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x63\x61lculator.proto\x12\ncalculator\"=\n\x16ProductDiscountRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\">\n\x17ProductDiscountResponse\x12\x0b\n\x03pct\x18\x01 \x01(\x01\x12\x16\n\x0evalue_in_cents\x18\x02 \x01(\x05\x32k\n\nCalculator\x12]\n\x12GetProductDiscount\x12\".calculator.ProductDiscountRequest\x1a#.calculator.ProductDiscountResponseb\x06proto3'
)




_PRODUCTDISCOUNTREQUEST = _descriptor.Descriptor(
  name='ProductDiscountRequest',
  full_name='calculator.ProductDiscountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='product_id', full_name='calculator.ProductDiscountRequest.product_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='calculator.ProductDiscountRequest.user_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=93,
)


_PRODUCTDISCOUNTRESPONSE = _descriptor.Descriptor(
  name='ProductDiscountResponse',
  full_name='calculator.ProductDiscountResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pct', full_name='calculator.ProductDiscountResponse.pct', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value_in_cents', full_name='calculator.ProductDiscountResponse.value_in_cents', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=157,
)

DESCRIPTOR.message_types_by_name['ProductDiscountRequest'] = _PRODUCTDISCOUNTREQUEST
DESCRIPTOR.message_types_by_name['ProductDiscountResponse'] = _PRODUCTDISCOUNTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProductDiscountRequest = _reflection.GeneratedProtocolMessageType('ProductDiscountRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTDISCOUNTREQUEST,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:calculator.ProductDiscountRequest)
  })
_sym_db.RegisterMessage(ProductDiscountRequest)

ProductDiscountResponse = _reflection.GeneratedProtocolMessageType('ProductDiscountResponse', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTDISCOUNTRESPONSE,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:calculator.ProductDiscountResponse)
  })
_sym_db.RegisterMessage(ProductDiscountResponse)



_CALCULATOR = _descriptor.ServiceDescriptor(
  name='Calculator',
  full_name='calculator.Calculator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=159,
  serialized_end=266,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetProductDiscount',
    full_name='calculator.Calculator.GetProductDiscount',
    index=0,
    containing_service=None,
    input_type=_PRODUCTDISCOUNTREQUEST,
    output_type=_PRODUCTDISCOUNTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATOR)

DESCRIPTOR.services_by_name['Calculator'] = _CALCULATOR

# @@protoc_insertion_point(module_scope)
